### ISSUE TITLE
RANSAC?

### ISSUE THREAD

**Issue by ducha-aiki** [simlocmatch/simlocmatch-benchmark#2]
Hi,

Can participants clear their matches with RANSAC?

**Comment by vbalnt** [comment]
Thanks Dmytro for the question. I will add a clarification section in the readme. 

TL;DR: Yes, participants can use whatever methods they see fit. 

- No restrictions on descriptor sizes, extraction methods, matching methods etc. 
- Since the matches are required for the end, it is responsibility of the participant of the method to perform some type of outlier filtering. 
- There is a freeform section in the submission template and the results website, where participants can explain what tricks/parameters they used for filtering.

**Comment by ducha-aiki** [comment]
Great, thank you!
